### ISSUE TITLE
MariaDB version 10.5.9 no longer supported by RDS

### ISSUE THREAD

**Issue by mbullmanFHCRC** [wcmc-its/ReCiter-CDK#1]
Hi, 

I'm trying to deploy to the cloud and have failed due to MariaDB 10.5.9 no longer being supported by RDS. Supported versions include 10.5.12 and 10.5.13, however, when trying to edit 
```
reciterDb = new DatabaseInstance(this, "reciterDb", DatabaseInstanceProps.builder()
            .engine(DatabaseInstanceEngine.mariaDb(MariaDbInstanceEngineProps.builder()
                .version(MariaDbEngineVersion.VER_10_5_9
```
manually to either 12 or 13 to attempt to deploy I run into symbol not found errors. I'm too unfamiliar with CDK and java compilation to attempt any further troubleshooting

Thanks,
Mike

**Comment by mbullmanFHCRC** [comment]
Just adding a screenshot of the failure
![Screen Shot 2021-12-15 at 8 54 42 AM](https://user-images.githubusercontent.com/53918926/146230319-a95dab6d-cab0-453e-9616-3e9c0c7880dd.png)

**Comment by mbullmanFHCRC** [comment]
solution for me

upgrade aws-cdk from 1.220.0(I think) to 1.134.0 `npm install -g aws-cdk@1.134.0`
change cdk version in pom.xml to 1.134.0 (line 35)
change mariaDB version to 10.5.12 in ReCiterCdkRDSStack.java from VER_10_5_9 to VER_10_5_12 (line 42)

successfully deployed on my end

**Comment by sarbajitdutta** [comment]
@mbullmanFHCRC I am updating the CDK version to the latest which is version 2. It should fix any version deprecation in any other resources as well. Also make sure to pull latest changes for ReCiter since we have patched the log4j vulnerability with the new release - https://github.com/wcmc-its/ReCiter/releases/tag/2.1.2
